"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-08-05 21:51:26.662663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_order_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_season_number', sa.Integer(), nullable=False),
    sa.Column('tmdb_episode_number', sa.Integer(), nullable=False),
    sa.Column('tmdb_episode_id', sa.Integer(), nullable=False),
    sa.Column('tvdb_series_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('tvdb_season_number', sa.Integer(), nullable=False),
    sa.Column('tvdb_episode_number', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_tmdb_id', 'tmdb_season_number', 'tmdb_episode_number', name='uq_episode_order_mapping_tmdb'),
    sa.UniqueConstraint('series_tmdb_id', 'tvdb_id', name='uq_episode_order_mapping_tvdb_id')
    )
    op.create_index('idx_episode_order_mapping_tvdb_position', 'episode_order_mappings', ['series_tmdb_id', 'tvdb_season_number', 'tvdb_episode_number'], unique=False)
    op.create_index('idx_episode_order_mapping_tvdb_series', 'episode_order_mappings', ['tvdb_series_id', 'tvdb_season_number'], unique=False)
    op.create_index(op.f('ix_episode_order_mappings_series_tmdb_id'), 'episode_order_mappings', ['series_tmdb_id'], unique=False)
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_api_key', sa.String(length=255), nullable=True),
    sa.Column('radarr_url', sa.String(length=500), nullable=True),
    sa.Column('radarr_token', sa.String(length=500), nullable=True),
    sa.Column('radarr_root_folder', sa.String(length=500), nullable=True),
    sa.Column('radarr_quality_profile', sa.Integer(), nullable=True),
    sa.Column('radarr_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sonarr_url', sa.String(length=500), nullable=True),
    sa.Column('sonarr_token', sa.String(length=500), nullable=True),
    sa.Column('sonarr_root_folder', sa.String(length=500), nullable=True),
    sa.Column('sonarr_quality_profile', sa.Integer(), nullable=True),
    sa.Column('sonarr_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sonarr_season_folder', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('radarr_require_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sonarr_require_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tvdb_api_key', sa.String(length=255), nullable=True),
    sa.Column('image_cache_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_cache_limit_gb', sa.Integer(), nullable=True),
    sa.Column('image_cache_expiry_days', sa.Integer(), nullable=True),
    sa.Column('enable_registrations', sa.Boolean(), nullable=True),
    sa.Column('registration_max_allowed_users', sa.Integer(), nullable=True),
    sa.Column('setup_completed', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_cache_type_accessed', 'image_cache', ['image_type', 'last_accessed'], unique=False)
    op.create_index('uq_image_cache_path_size', 'image_cache', ['path', 'size'], unique=True)
    op.create_table('media_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'series', 'episode', 'person', name='mediatype'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', 'media_type', name='uq_media_aliases_provider_external_type')
    )
    op.create_index('idx_media_aliases_internal_type', 'media_aliases', ['internal_id', 'media_type'], unique=False)
    op.create_table('provider_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index('idx_provider_cache_expires', 'provider_cache', ['expires_at'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('uri_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('content_rating', sa.String(length=16), nullable=True),
    sa.Column('tmdb_rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('first_air_date', sa.String(length=20), nullable=True),
    sa.Column('last_air_date', sa.String(length=20), nullable=True),
    sa.Column('tmdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tvdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_title', sa.String(length=500), nullable=True),
    sa.Column('custom_season_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id'),
    sa.UniqueConstraint('tvdb_id')
    )
    op.create_index(op.f('ix_shows_uri_id'), 'shows', ['uri_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('plex_account_id', sa.String(length=64), nullable=True),
    sa.Column('plex_username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_plex_account_id'), 'users', ['plex_account_id'], unique=True)
    op.create_table('blocklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uri_id', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.Enum('movie', 'series', 'episode', 'person', name='mediatype'), nullable=False),
    sa.Column('is_dropped', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'uri_id', name='uq_blocklist_user_uri')
    )
    op.create_index(op.f('ix_blocklist_items_uri_id'), 'blocklist_items', ['uri_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('uri_id', sa.String(length=50), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_uri', 'comments', ['media_type', 'uri_id', 'season_number', 'episode_number'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('email_activations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_email_activations_user_id'), 'email_activations', ['user_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow')
    )
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('privacy_level', sa.Enum('public', 'friends_only', 'private', name='privacylevel'), server_default='private', nullable=False),
    sa.Column('trakt_slug', sa.String(length=255), nullable=True),
    sa.Column('mdblist_slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('radarr_auto_add', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('radarr_root_folder', sa.String(length=500), nullable=True),
    sa.Column('radarr_quality_profile', sa.Integer(), nullable=True),
    sa.Column('radarr_tags', sa.JSON(), nullable=True),
    sa.Column('radarr_monitor', sa.String(length=50), nullable=True),
    sa.Column('sonarr_auto_add', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sonarr_root_folder', sa.String(length=500), nullable=True),
    sa.Column('sonarr_quality_profile', sa.Integer(), nullable=True),
    sa.Column('sonarr_tags', sa.JSON(), nullable=True),
    sa.Column('sonarr_series_type', sa.String(length=50), nullable=True),
    sa.Column('sonarr_season_folder', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sonarr_monitor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('uri_id', sa.String(length=50), nullable=True),
    sa.Column('media_type', sa.Enum('movie', 'series', 'episode', 'person', name='mediatype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('backdrop_path', sa.String(length=500), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('tmdb_rating', sa.Float(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('tmdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tvdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adult', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('custom_title', sa.String(length=500), nullable=True),
    sa.Column('content_rating', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_media_show_season_episode', 'media', ['show_id', 'season_number', 'episode_number'], unique=False)
    op.create_index('idx_media_tmdb_type', 'media', ['tmdb_id', 'media_type'], unique=False)
    op.create_index('idx_media_type_release_date', 'media', ['media_type', 'release_date'], unique=False)
    op.create_index('idx_media_type_tmdb_rating', 'media', ['media_type', 'tmdb_rating'], unique=False)
    op.create_index(op.f('ix_media_uri_id'), 'media', ['uri_id'], unique=False)
    op.create_table('media_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uri_id', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus'), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_requests_uri_id'), 'media_requests', ['uri_id'], unique=False)
    op.create_table('media_server_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('server_user_id', sa.String(length=255), nullable=True),
    sa.Column('server_username', sa.String(length=255), nullable=True),
    sa.Column('external_server_url', sa.String(length=500), nullable=True),
    sa.Column('sync_collection', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_watched', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_ratings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_playback', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('push_watched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('push_collection', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('push_playback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('push_ratings', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('auto_sync_interval', sa.Float(), nullable=True),
    sa.Column('partial_sync_interval', sa.Float(), nullable=True),
    sa.Column('auto_push_interval', sa.Float(), nullable=True),
    sa.Column('last_full_sync', sa.DateTime(), nullable=True),
    sa.Column('last_partial_sync', sa.DateTime(), nullable=True),
    sa.Column('watchlist_to_radarr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('watchlist_to_sonarr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('watchlist_all_users', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('watchlist_monitored_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('watchlist_synced_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stremio_pull_cursor_at', sa.DateTime(), nullable=True),
    sa.Column('stremio_full_sync_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('stremio_pushed_library_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plex_sync_watchlist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('plex_push_watchlist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_server_connections_user_id'), 'media_server_connections', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('scrobble_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('server_user_id', sa.String(length=255), nullable=True),
    sa.Column('server_username', sa.String(length=255), nullable=True),
    sa.Column('sync_collection', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_watched', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sync_playback', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrobble_connections_user_id'), 'scrobble_connections', ['user_id'], unique=False)
    op.create_table('show_episode_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_show_id', sa.Integer(), nullable=False),
    sa.Column('source_season_number', sa.Integer(), nullable=False),
    sa.Column('source_episode_number', sa.Integer(), nullable=False),
    sa.Column('target_show_id', sa.Integer(), nullable=True),
    sa.Column('target_season_number', sa.Integer(), nullable=False),
    sa.Column('target_episode_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_show_id', 'source_season_number', 'source_episode_number', name='uq_episode_override')
    )
    op.create_table('show_season_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_show_id', sa.Integer(), nullable=False),
    sa.Column('source_season_number', sa.Integer(), nullable=False),
    sa.Column('target_show_id', sa.Integer(), nullable=True),
    sa.Column('target_season_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_show_id', 'source_season_number', name='uq_season_override')
    )
    op.create_table('show_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'language', name='uq_show_translations_show_language')
    )
    op.create_index(op.f('ix_show_translations_show_id'), 'show_translations', ['show_id'], unique=False)
    op.create_table('totp_backup_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_totp_backup_codes_user_id'), 'totp_backup_codes', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('liked_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disliked_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('streaming_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_language', sa.String(length=10), nullable=True),
    sa.Column('metadata_language', sa.String(length=10), nullable=True),
    sa.Column('privacy_level', sa.Enum('public', 'friends_only', 'private', name='privacylevel'), server_default='private', nullable=False),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('pagination_type', sa.String(length=20), server_default='infinite_scroll', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_api_key', sa.String(length=255), nullable=True),
    sa.Column('radarr_url', sa.String(length=500), nullable=True),
    sa.Column('radarr_token', sa.String(length=500), nullable=True),
    sa.Column('radarr_root_folder', sa.String(length=500), nullable=True),
    sa.Column('radarr_quality_profile', sa.Integer(), nullable=True),
    sa.Column('radarr_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sonarr_url', sa.String(length=500), nullable=True),
    sa.Column('sonarr_token', sa.String(length=500), nullable=True),
    sa.Column('sonarr_root_folder', sa.String(length=500), nullable=True),
    sa.Column('sonarr_quality_profile', sa.Integer(), nullable=True),
    sa.Column('sonarr_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sonarr_season_folder', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trakt_client_id', sa.String(length=255), nullable=True),
    sa.Column('trakt_client_secret', sa.String(length=255), nullable=True),
    sa.Column('trakt_access_token', sa.String(length=2000), nullable=True),
    sa.Column('trakt_refresh_token', sa.String(length=2000), nullable=True),
    sa.Column('trakt_token_expires_at', sa.BigInteger(), nullable=True),
    sa.Column('trakt_device_code', sa.String(length=255), nullable=True),
    sa.Column('trakt_sync_watched', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trakt_sync_ratings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trakt_history_cursor_at', sa.DateTime(), nullable=True),
    sa.Column('trakt_push_watched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_push_ratings', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_push_collection', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_scrobble', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_sync_lists', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_push_lists', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_watchlist_split', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trakt_auto_sync_interval', sa.Float(), nullable=True),
    sa.Column('trakt_auto_push_interval', sa.Float(), nullable=True),
    sa.Column('tvdb_api_key', sa.String(length=255), nullable=True),
    sa.Column('simkl_client_id', sa.String(length=255), nullable=True),
    sa.Column('simkl_access_token', sa.String(length=2000), nullable=True),
    sa.Column('simkl_device_code', sa.String(length=255), nullable=True),
    sa.Column('simkl_sync_watched', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('simkl_sync_ratings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('simkl_sync_lists', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('simkl_push_watched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('simkl_push_ratings', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('simkl_scrobble', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('simkl_auto_sync_interval', sa.Float(), nullable=True),
    sa.Column('simkl_auto_push_interval', sa.Float(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blur_explicit', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_comments', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_user_ratings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('time_format_24h', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('use_hls_player', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('playback_target', sa.String(length=20), server_default='web', nullable=False),
    sa.Column('default_episode_order', sa.String(length=20), server_default='tmdb', nullable=False),
    sa.Column('onboarded', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trakt_full_sync_interval', sa.Integer(), nullable=True),
    sa.Column('trakt_partial_sync_interval', sa.Integer(), nullable=True),
    sa.Column('last_trakt_full_sync', sa.DateTime(), nullable=True),
    sa.Column('last_trakt_partial_sync', sa.DateTime(), nullable=True),
    sa.Column('shuffle_next_up', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('minimalist_next_up', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mdblist_api_key', sa.String(length=255), nullable=True),
    sa.Column('mdblist_sync_watched', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mdblist_sync_ratings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mdblist_sync_watchlist', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mdblist_push_watched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mdblist_push_ratings', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mdblist_push_watchlist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mdblist_push_collection', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mdblist_scrobble', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mdblist_auto_sync_interval', sa.Float(), nullable=True),
    sa.Column('mdblist_auto_push_interval', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_show_episode_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('episode_order', sa.String(length=20), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'series_tmdb_id', name='uq_user_show_episode_order')
    )
    op.create_index(op.f('ix_user_show_episode_orders_series_tmdb_id'), 'user_show_episode_orders', ['series_tmdb_id'], unique=False)
    op.create_index(op.f('ix_user_show_episode_orders_user_id'), 'user_show_episode_orders', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_collection_user_media')
    )
    op.create_index('idx_collections_media_id', 'collections', ['media_id'], unique=False)
    op.create_table('emby_library_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.String(length=255), nullable=False),
    sa.Column('library_name', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['media_server_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'library_id')
    )
    op.create_table('episode_movie_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('original_show_id', sa.Integer(), nullable=True),
    sa.Column('original_season_number', sa.Integer(), nullable=True),
    sa.Column('original_episode_number', sa.Integer(), nullable=True),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('original_tmdb_id', sa.Integer(), nullable=True),
    sa.Column('movie_tmdb_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_show_id'], ['shows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_episode_movie_conversion')
    )
    op.create_table('jellyfin_library_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.String(length=255), nullable=False),
    sa.Column('library_name', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['media_server_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'library_id')
    )
    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'media_id', name='uq_list_item')
    )
    op.create_table('media_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'language', name='uq_media_translations_media_language')
    )
    op.create_index(op.f('ix_media_translations_media_id'), 'media_translations', ['media_id'], unique=False)
    op.create_table('playback_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_playback_progress_user_media')
    )
    op.create_index('idx_playback_progress_user_media', 'playback_progress', ['user_id', 'media_id'], unique=False)
    op.create_table('playback_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('progress_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_index('idx_playback_sessions_session_key', 'playback_sessions', ['session_key'], unique=False)
    op.create_table('plex_library_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('library_key', sa.String(length=255), nullable=False),
    sa.Column('library_name', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['media_server_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'library_key')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_order', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('jellyfin', 'emby', 'plex', 'nuvio', 'stremio', 'trakt', 'simkl', 'mdblist', 'manual', 'tmdb', name='collectionsource'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='syncstatus'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=20), server_default='pull', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['media_server_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('progress_seconds', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watch_events_user_completed_watched_at', 'watch_events', ['user_id', 'completed', 'watched_at'], unique=False)
    op.create_index('idx_watch_events_user_media', 'watch_events', ['user_id', 'media_id'], unique=False)
    op.create_table('collection_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('jellyfin', 'emby', 'plex', 'nuvio', 'stremio', 'trakt', 'simkl', 'mdblist', 'manual', 'tmdb', name='collectionsource'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_channels', sa.String(length=20), nullable=True),
    sa.Column('audio_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subtitle_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_id'], ['media_server_connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'source', 'source_id', name='uq_collection_file_source')
    )
    op.create_index('idx_collection_files_collection_id', 'collection_files', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_files_connection_id'), 'collection_files', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_files_connection_id'), table_name='collection_files')
    op.drop_index('idx_collection_files_collection_id', table_name='collection_files')
    op.drop_table('collection_files')
    op.drop_index('idx_watch_events_user_media', table_name='watch_events')
    op.drop_index('idx_watch_events_user_completed_watched_at', table_name='watch_events')
    op.drop_table('watch_events')
    op.drop_table('sync_jobs')
    op.drop_table('ratings')
    op.drop_table('plex_library_selections')
    op.drop_index('idx_playback_sessions_session_key', table_name='playback_sessions')
    op.drop_table('playback_sessions')
    op.drop_index('idx_playback_progress_user_media', table_name='playback_progress')
    op.drop_table('playback_progress')
    op.drop_index(op.f('ix_media_translations_media_id'), table_name='media_translations')
    op.drop_table('media_translations')
    op.drop_table('list_items')
    op.drop_table('jellyfin_library_selections')
    op.drop_table('episode_movie_conversions')
    op.drop_table('emby_library_selections')
    op.drop_index('idx_collections_media_id', table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_user_show_episode_orders_user_id'), table_name='user_show_episode_orders')
    op.drop_index(op.f('ix_user_show_episode_orders_series_tmdb_id'), table_name='user_show_episode_orders')
    op.drop_table('user_show_episode_orders')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_totp_backup_codes_user_id'), table_name='totp_backup_codes')
    op.drop_table('totp_backup_codes')
    op.drop_index(op.f('ix_show_translations_show_id'), table_name='show_translations')
    op.drop_table('show_translations')
    op.drop_table('show_season_overrides')
    op.drop_table('show_episode_overrides')
    op.drop_index(op.f('ix_scrobble_connections_user_id'), table_name='scrobble_connections')
    op.drop_table('scrobble_connections')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_media_server_connections_user_id'), table_name='media_server_connections')
    op.drop_table('media_server_connections')
    op.drop_index(op.f('ix_media_requests_uri_id'), table_name='media_requests')
    op.drop_table('media_requests')
    op.drop_index(op.f('ix_media_uri_id'), table_name='media')
    op.drop_index('idx_media_type_tmdb_rating', table_name='media')
    op.drop_index('idx_media_type_release_date', table_name='media')
    op.drop_index('idx_media_tmdb_type', table_name='media')
    op.drop_index('idx_media_show_season_episode', table_name='media')
    op.drop_table('media')
    op.drop_table('lists')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_email_activations_user_id'), table_name='email_activations')
    op.drop_table('email_activations')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index('idx_comments_uri', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_blocklist_items_uri_id'), table_name='blocklist_items')
    op.drop_table('blocklist_items')
    op.drop_index(op.f('ix_users_plex_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shows_uri_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_index('idx_provider_cache_expires', table_name='provider_cache')
    op.drop_table('provider_cache')
    op.drop_index('idx_media_aliases_internal_type', table_name='media_aliases')
    op.drop_table('media_aliases')
    op.drop_index('uq_image_cache_path_size', table_name='image_cache')
    op.drop_index('idx_image_cache_type_accessed', table_name='image_cache')
    op.drop_table('image_cache')
    op.drop_table('global_settings')
    op.drop_index(op.f('ix_episode_order_mappings_series_tmdb_id'), table_name='episode_order_mappings')
    op.drop_index('idx_episode_order_mapping_tvdb_position', table_name='episode_order_mappings')
    op.drop_table('episode_order_mappings')
    # ### end Alembic commands ###
