"""uri-based media identity and merged feature tables

Revision ID: 01bd56990a60
Revises: imgcachefloat
Create Date: 2026-09-02

Autogenerated from the merged metadata, then hand-finished. Three classes of
change autogenerate got wrong on a populated database and that are corrected
here:

  * `comments.uri_id`, `media_requests.uri_id` and
    `show_season_overrides.source_show_id` are NOT NULL with no default, so
    adding them straight would fail on any existing row. Each is added
    nullable, backfilled, then promoted.

  * The columns they replace - `comments.tmdb_id`, `media_requests.tmdb_id`,
    the three `show_season_overrides.*_tmdb_id`/`*_tvdb_id` columns and
    `user_profiles.{show,movie}_genres` - carry the only copy of that data.
    Dropping them before converting would lose every comment's subject, every
    request's target, every season remap and every genre preference.

  * Autogenerate wanted to drop `uq_media_tmdb_type`, `uq_rating_user_media_
    season_order` and `uq_list_item_season`. Those indexes are created by
    earlier migrations and have never been declared on the models, so
    autogenerate has always wanted to drop them - they are deliberately kept.
    `create_media_safely` depends on `uq_media_tmdb_type` raising
    IntegrityError to detect a lost create race (#157); without it duplicate
    media rows come back silently.

`media.uri_id` and `shows.uri_id` stay nullable, matching the models: a row
with no provider id at all cannot be addressed and is left unstamped.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '01bd56990a60'
down_revision: Union[str, Sequence[str], None] = 'imgcachefloat'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# media_type -> MediaURI type code, mirroring models/media.py _URI_TYPE_CODE
_URI_CODE_SQL = "CASE {col}::text WHEN 'movie' THEN 'm' WHEN 'series' THEN 's' WHEN 'episode' THEN 'e' END"


def upgrade() -> None:
    """Upgrade schema."""
    # ── new tables ───────────────────────────────────────────────────────────
    op.create_table(
        'media_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('internal_id', sa.Integer(), nullable=False),
        sa.Column('media_type', postgresql.ENUM('movie', 'series', 'episode', 'person', name='mediatype', create_type=False), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('external_id', sa.String(length=100), nullable=False),
        sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider', 'external_id', 'media_type', name='uq_media_aliases_provider_external_type'),
    )
    op.create_table(
        'provider_cache',
        sa.Column('cache_key', sa.String(length=64), nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('cache_key'),
    )
    op.create_table(
        'blocklist_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('uri_id', sa.String(length=50), nullable=False),
        sa.Column('media_type', postgresql.ENUM('movie', 'series', 'episode', 'person', name='mediatype', create_type=False), nullable=False),
        sa.Column('is_dropped', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'uri_id', name='uq_blocklist_user_uri'),
    )
    op.create_table(
        'show_episode_overrides',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('source_show_id', sa.Integer(), nullable=False),
        sa.Column('source_season_number', sa.Integer(), nullable=False),
        sa.Column('source_episode_number', sa.Integer(), nullable=False),
        sa.Column('target_show_id', sa.Integer(), nullable=True),
        sa.Column('target_season_number', sa.Integer(), nullable=False),
        sa.Column('target_episode_number', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source_show_id'], ['shows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_show_id'], ['shows.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'source_show_id', 'source_season_number', 'source_episode_number', name='uq_episode_override'),
    )
    op.create_table(
        'episode_movie_conversions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('media_id', sa.Integer(), nullable=False),
        sa.Column('original_show_id', sa.Integer(), nullable=True),
        sa.Column('original_season_number', sa.Integer(), nullable=True),
        sa.Column('original_episode_number', sa.Integer(), nullable=True),
        sa.Column('original_title', sa.String(length=500), nullable=True),
        sa.Column('original_tmdb_id', sa.Integer(), nullable=True),
        sa.Column('movie_tmdb_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['original_show_id'], ['shows.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'media_id', name='uq_episode_movie_conversion'),
    )

    op.create_index('idx_media_aliases_internal_type', 'media_aliases', ['internal_id', 'media_type'], unique=False)
    op.create_index('idx_provider_cache_expires', 'provider_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_blocklist_items_uri_id'), 'blocklist_items', ['uri_id'], unique=False)

    # ── purely additive columns ──────────────────────────────────────────────
    op.add_column('global_settings', sa.Column('image_cache_expiry_days', sa.Integer(), nullable=True))
    op.add_column('global_settings', sa.Column('enable_registrations', sa.Boolean(), nullable=True))
    op.add_column('global_settings', sa.Column('registration_max_allowed_users', sa.Integer(), nullable=True))
    # server_default true: an existing install has already been set up and must
    # not be sent back through the first-run wizard.
    op.add_column('global_settings', sa.Column('setup_completed', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('global_settings', 'image_cache_limit_gb',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using='round(image_cache_limit_gb)::integer')

    for col in (
        sa.Column('radarr_auto_add', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('radarr_root_folder', sa.String(length=500), nullable=True),
        sa.Column('radarr_quality_profile', sa.Integer(), nullable=True),
        sa.Column('radarr_tags', sa.JSON(), nullable=True),
        sa.Column('radarr_monitor', sa.String(length=50), nullable=True),
        sa.Column('sonarr_auto_add', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('sonarr_root_folder', sa.String(length=500), nullable=True),
        sa.Column('sonarr_quality_profile', sa.Integer(), nullable=True),
        sa.Column('sonarr_tags', sa.JSON(), nullable=True),
        sa.Column('sonarr_series_type', sa.String(length=50), nullable=True),
        sa.Column('sonarr_season_folder', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('sonarr_monitor', sa.String(length=50), nullable=True),
    ):
        op.add_column('lists', col)

    op.add_column('media', sa.Column('uri_id', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('tvdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('media', sa.Column('custom_title', sa.String(length=500), nullable=True))
    op.add_column('media', sa.Column('content_rating', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_media_uri_id'), 'media', ['uri_id'], unique=False)

    op.add_column('shows', sa.Column('uri_id', sa.String(length=50), nullable=True))
    op.add_column('shows', sa.Column('content_rating', sa.String(length=16), nullable=True))
    op.add_column('shows', sa.Column('tvdb_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('shows', sa.Column('custom_title', sa.String(length=500), nullable=True))
    op.add_column('shows', sa.Column('custom_season_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_shows_uri_id'), 'shows', ['uri_id'], unique=False)

    op.add_column('media_server_connections', sa.Column('external_server_url', sa.String(length=500), nullable=True))
    op.add_column('media_server_connections', sa.Column('partial_sync_interval', sa.Float(), nullable=True))
    op.add_column('media_server_connections', sa.Column('last_full_sync', sa.DateTime(), nullable=True))
    op.add_column('media_server_connections', sa.Column('last_partial_sync', sa.DateTime(), nullable=True))

    op.add_column('user_settings', sa.Column('show_comments', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('show_user_ratings', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('playback_target', sa.String(length=20), server_default='web', nullable=False))
    op.add_column('user_settings', sa.Column('default_episode_order', sa.String(length=20), server_default='tmdb', nullable=False))
    # true for existing accounts: they have been using the app already.
    op.add_column('user_settings', sa.Column('onboarded', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('trakt_full_sync_interval', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('trakt_partial_sync_interval', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('last_trakt_full_sync', sa.DateTime(), nullable=True))
    op.add_column('user_settings', sa.Column('last_trakt_partial_sync', sa.DateTime(), nullable=True))

    op.add_column('users', sa.Column('plex_account_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('plex_username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_plex_account_id'), 'users', ['plex_account_id'], unique=True)

    # ── backfill: stamp a uri on every addressable existing row ──────────────
    # Mirrors _stamp_show_uri / stamp_media_uri: TMDB wins, TVDB is the
    # fallback, and a row with neither stays NULL rather than being invented.
    op.execute("UPDATE shows SET uri_id = 'tmdb:s:' || tmdb_id WHERE uri_id IS NULL AND tmdb_id IS NOT NULL")
    op.execute("UPDATE shows SET uri_id = 'tvdb:s:' || tvdb_id WHERE uri_id IS NULL AND tvdb_id IS NOT NULL")
    op.execute(
        "UPDATE media SET uri_id = 'tmdb:' || " + _URI_CODE_SQL.format(col='media_type') + " || ':' || tmdb_id "
        "WHERE uri_id IS NULL AND tmdb_id IS NOT NULL AND media_type::text IN ('movie', 'series', 'episode')"
    )

    # Seed the alias registry from the ids shows already carry, so a lookup
    # arriving with the provider a row was *not* keyed on still resolves.
    op.execute(
        "INSERT INTO media_aliases (internal_id, media_type, provider, external_id) "
        "SELECT id, 'series'::mediatype, 'tmdb', tmdb_id::text FROM shows WHERE tmdb_id IS NOT NULL "
        "ON CONFLICT ON CONSTRAINT uq_media_aliases_provider_external_type DO NOTHING"
    )
    op.execute(
        "INSERT INTO media_aliases (internal_id, media_type, provider, external_id) "
        "SELECT id, 'series'::mediatype, 'tvdb', tvdb_id::text FROM shows WHERE tvdb_id IS NOT NULL "
        "ON CONFLICT ON CONSTRAINT uq_media_aliases_provider_external_type DO NOTHING"
    )

    # ── comments: tmdb_id -> uri_id ──────────────────────────────────────────
    op.add_column('comments', sa.Column('uri_id', sa.String(length=50), nullable=True))
    op.execute(
        "UPDATE comments SET uri_id = 'tmdb:' || " + _URI_CODE_SQL.format(col='media_type') + " || ':' || tmdb_id "
        "WHERE media_type IN ('movie', 'series', 'episode')"
    )
    # A comment on an unrecognised media_type has no uri form; keep the row
    # addressable rather than dropping it.
    op.execute("UPDATE comments SET uri_id = 'tmdb:m:' || tmdb_id WHERE uri_id IS NULL")
    op.alter_column('comments', 'uri_id', nullable=False)
    op.drop_index(op.f('idx_comments_media'), table_name='comments')
    op.create_index('idx_comments_uri', 'comments', ['media_type', 'uri_id', 'season_number', 'episode_number'], unique=False)
    op.drop_column('comments', 'tmdb_id')

    # ── media_requests: tmdb_id -> uri_id ────────────────────────────────────
    op.add_column('media_requests', sa.Column('uri_id', sa.String(length=50), nullable=True))
    op.add_column('media_requests', sa.Column('season_number', sa.Integer(), nullable=True))
    op.add_column('media_requests', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE media_requests SET uri_id = 'tmdb:' || " + _URI_CODE_SQL.format(col='media_type') + " || ':' || tmdb_id "
        "WHERE media_type IN ('movie', 'series', 'episode')"
    )
    op.execute("UPDATE media_requests SET uri_id = 'tmdb:m:' || tmdb_id WHERE uri_id IS NULL")
    op.alter_column('media_requests', 'uri_id', nullable=False)
    op.drop_index(op.f('ix_media_requests_user_tmdb'), table_name='media_requests')
    op.create_index(op.f('ix_media_requests_uri_id'), 'media_requests', ['uri_id'], unique=False)
    op.drop_column('media_requests', 'tmdb_id')

    # ── season overrides: provider ids -> show foreign keys ──────────────────
    op.add_column('show_season_overrides', sa.Column('source_show_id', sa.Integer(), nullable=True))
    op.add_column('show_season_overrides', sa.Column('target_show_id', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE show_season_overrides o SET source_show_id = s.id "
        "FROM shows s WHERE s.tmdb_id = o.source_show_tmdb_id"
    )
    op.execute(
        "UPDATE show_season_overrides o SET target_show_id = s.id "
        "FROM shows s WHERE o.target_show_tmdb_id IS NOT NULL AND s.tmdb_id = o.target_show_tmdb_id"
    )
    op.execute(
        "UPDATE show_season_overrides o SET target_show_id = s.id "
        "FROM shows s WHERE o.target_show_id IS NULL AND o.target_show_tvdb_id IS NOT NULL "
        "AND s.tvdb_id = o.target_show_tvdb_id"
    )
    # An override whose source show is not in the library could never have been
    # applied - there is no row for it to remap - and source_show_id is NOT NULL.
    op.execute("DELETE FROM show_season_overrides WHERE source_show_id IS NULL")
    op.alter_column('show_season_overrides', 'source_show_id', nullable=False)
    op.drop_constraint(op.f('uq_season_override'), 'show_season_overrides', type_='unique')
    op.create_unique_constraint('uq_season_override', 'show_season_overrides', ['user_id', 'source_show_id', 'source_season_number'])
    op.create_foreign_key('fk_season_override_source_show', 'show_season_overrides', 'shows', ['source_show_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_season_override_target_show', 'show_season_overrides', 'shows', ['target_show_id'], ['id'], ondelete='SET NULL')
    op.drop_column('show_season_overrides', 'target_show_tmdb_id')
    op.drop_column('show_season_overrides', 'target_show_tvdb_id')
    op.drop_column('show_season_overrides', 'source_show_tmdb_id')

    # ── profiles: separate movie/show genre lists -> one liked_genres ────────
    op.add_column('user_profiles', sa.Column('liked_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('pagination_type', sa.String(length=20), server_default='infinite_scroll', nullable=False))
    op.execute(
        "UPDATE user_profiles SET liked_genres = ( "
        "  SELECT COALESCE(jsonb_agg(DISTINCT g), '[]'::jsonb) FROM ( "
        "    SELECT jsonb_array_elements(COALESCE(movie_genres, '[]'::jsonb)) AS g "
        "    UNION "
        "    SELECT jsonb_array_elements(COALESCE(show_genres, '[]'::jsonb)) AS g "
        "  ) AS merged "
        ") "
        "WHERE movie_genres IS NOT NULL OR show_genres IS NOT NULL"
    )
    op.drop_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', type_='unique')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.drop_column('user_profiles', 'show_genres')
    op.drop_column('user_profiles', 'movie_genres')

    # ── index housekeeping the models now express differently ────────────────
    op.drop_index(op.f('idx_media_translations_media_id'), table_name='media_translations')
    op.drop_index(op.f('uq_media_translations_media_language'), table_name='media_translations')
    op.create_unique_constraint('uq_media_translations_media_language', 'media_translations', ['media_id', 'language'])
    op.create_index(op.f('ix_media_translations_media_id'), 'media_translations', ['media_id'], unique=False)
    op.drop_index(op.f('idx_show_translations_show_id'), table_name='show_translations')
    op.drop_index(op.f('uq_show_translations_show_language'), table_name='show_translations')
    op.create_unique_constraint('uq_show_translations_show_language', 'show_translations', ['show_id', 'language'])
    op.create_index(op.f('ix_show_translations_show_id'), 'show_translations', ['show_id'], unique=False)
    op.drop_constraint(op.f('uq_oauth_device_grants_device_code_hash'), 'oauth_device_grants', type_='unique')
    op.drop_constraint(op.f('uq_oauth_device_grants_user_code'), 'oauth_device_grants', type_='unique')
    op.drop_index(op.f('ix_oauth_device_grants_device_code_hash'), table_name='oauth_device_grants')
    op.create_index(op.f('ix_oauth_device_grants_device_code_hash'), 'oauth_device_grants', ['device_code_hash'], unique=True)
    op.drop_index(op.f('ix_oauth_device_grants_user_code'), table_name='oauth_device_grants')
    op.create_index(op.f('ix_oauth_device_grants_user_code'), 'oauth_device_grants', ['user_code'], unique=True)

    # NOT dropped, against autogenerate's advice - see the module docstring:
    #   uq_media_tmdb_type, uq_rating_user_media_season_order, uq_list_item_season


def downgrade() -> None:
    """Downgrade schema.

    Best effort. The uri backfill is not reversed field by field: comments and
    requests recover their tmdb_id from the uri, season overrides recover their
    provider ids from the shows they point at, and liked_genres is written back
    to both movie_genres and show_genres because the split it replaced cannot
    be reconstructed.
    """
    op.add_column('user_profiles', sa.Column('movie_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('show_genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE user_profiles SET movie_genres = liked_genres, show_genres = liked_genres WHERE liked_genres IS NOT NULL")
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', ['user_id'])
    op.drop_column('user_profiles', 'pagination_type')
    op.drop_column('user_profiles', 'liked_genres')

    op.add_column('show_season_overrides', sa.Column('source_show_tmdb_id', sa.Integer(), nullable=True))
    op.add_column('show_season_overrides', sa.Column('target_show_tvdb_id', sa.Integer(), nullable=True))
    op.add_column('show_season_overrides', sa.Column('target_show_tmdb_id', sa.Integer(), nullable=True))
    op.execute("UPDATE show_season_overrides o SET source_show_tmdb_id = s.tmdb_id FROM shows s WHERE s.id = o.source_show_id")
    op.execute("UPDATE show_season_overrides o SET target_show_tmdb_id = s.tmdb_id, target_show_tvdb_id = s.tvdb_id FROM shows s WHERE s.id = o.target_show_id")
    op.execute("DELETE FROM show_season_overrides WHERE source_show_tmdb_id IS NULL")
    op.alter_column('show_season_overrides', 'source_show_tmdb_id', nullable=False)
    op.drop_constraint('fk_season_override_target_show', 'show_season_overrides', type_='foreignkey')
    op.drop_constraint('fk_season_override_source_show', 'show_season_overrides', type_='foreignkey')
    op.drop_constraint(op.f('uq_season_override'), 'show_season_overrides', type_='unique')
    op.create_unique_constraint('uq_season_override', 'show_season_overrides', ['user_id', 'source_show_tmdb_id', 'source_season_number'])
    op.drop_column('show_season_overrides', 'target_show_id')
    op.drop_column('show_season_overrides', 'source_show_id')

    op.add_column('media_requests', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.execute("UPDATE media_requests SET tmdb_id = split_part(uri_id, ':', 3)::integer WHERE uri_id ~ '^[a-z]+:[smep]:[0-9]+$'")
    op.execute("DELETE FROM media_requests WHERE tmdb_id IS NULL")
    op.alter_column('media_requests', 'tmdb_id', nullable=False)
    op.drop_index(op.f('ix_media_requests_uri_id'), table_name='media_requests')
    op.create_index(op.f('ix_media_requests_user_tmdb'), 'media_requests', ['user_id', 'tmdb_id', 'media_type'], unique=False)
    op.drop_column('media_requests', 'episode_number')
    op.drop_column('media_requests', 'season_number')
    op.drop_column('media_requests', 'uri_id')

    op.add_column('comments', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.execute("UPDATE comments SET tmdb_id = split_part(uri_id, ':', 3)::integer WHERE uri_id ~ '^[a-z]+:[smep]:[0-9]+$'")
    op.execute("DELETE FROM comments WHERE tmdb_id IS NULL")
    op.alter_column('comments', 'tmdb_id', nullable=False)
    op.drop_index('idx_comments_uri', table_name='comments')
    op.create_index(op.f('idx_comments_media'), 'comments', ['media_type', 'tmdb_id', 'season_number', 'episode_number'], unique=False)
    op.drop_column('comments', 'uri_id')

    op.drop_index(op.f('ix_users_plex_account_id'), table_name='users')
    op.drop_column('users', 'plex_username')
    op.drop_column('users', 'plex_account_id')
    for name in ('last_trakt_partial_sync', 'last_trakt_full_sync', 'trakt_partial_sync_interval',
                 'trakt_full_sync_interval', 'onboarded', 'default_episode_order', 'playback_target',
                 'show_user_ratings', 'show_comments'):
        op.drop_column('user_settings', name)
    for name in ('last_partial_sync', 'last_full_sync', 'partial_sync_interval', 'external_server_url'):
        op.drop_column('media_server_connections', name)

    op.drop_index(op.f('ix_shows_uri_id'), table_name='shows')
    for name in ('custom_season_names', 'custom_title', 'tvdb_data', 'content_rating', 'uri_id'):
        op.drop_column('shows', name)
    op.drop_index(op.f('ix_media_uri_id'), table_name='media')
    for name in ('content_rating', 'custom_title', 'tvdb_data', 'uri_id'):
        op.drop_column('media', name)
    for name in ('sonarr_monitor', 'sonarr_season_folder', 'sonarr_series_type', 'sonarr_tags',
                 'sonarr_quality_profile', 'sonarr_root_folder', 'sonarr_auto_add', 'radarr_monitor',
                 'radarr_tags', 'radarr_quality_profile', 'radarr_root_folder', 'radarr_auto_add'):
        op.drop_column('lists', name)

    op.alter_column('global_settings', 'image_cache_limit_gb',
                    existing_type=sa.Integer(),
                    type_=sa.DOUBLE_PRECISION(precision=53),
                    existing_nullable=True)
    for name in ('setup_completed', 'registration_max_allowed_users', 'enable_registrations', 'image_cache_expiry_days'):
        op.drop_column('global_settings', name)

    op.drop_index(op.f('ix_show_translations_show_id'), table_name='show_translations')
    op.drop_constraint('uq_show_translations_show_language', 'show_translations', type_='unique')
    op.create_index(op.f('idx_show_translations_show_id'), 'show_translations', ['show_id'], unique=False)
    op.create_index(op.f('uq_show_translations_show_language'), 'show_translations', ['show_id', 'language'], unique=True)
    op.drop_index(op.f('ix_media_translations_media_id'), table_name='media_translations')
    op.drop_constraint('uq_media_translations_media_language', 'media_translations', type_='unique')
    op.create_index(op.f('idx_media_translations_media_id'), 'media_translations', ['media_id'], unique=False)
    op.create_index(op.f('uq_media_translations_media_language'), 'media_translations', ['media_id', 'language'], unique=True)
    op.drop_index(op.f('ix_oauth_device_grants_user_code'), table_name='oauth_device_grants')
    op.create_index(op.f('ix_oauth_device_grants_user_code'), 'oauth_device_grants', ['user_code'], unique=False)
    op.drop_index(op.f('ix_oauth_device_grants_device_code_hash'), table_name='oauth_device_grants')
    op.create_index(op.f('ix_oauth_device_grants_device_code_hash'), 'oauth_device_grants', ['device_code_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_oauth_device_grants_user_code'), 'oauth_device_grants', ['user_code'])
    op.create_unique_constraint(op.f('uq_oauth_device_grants_device_code_hash'), 'oauth_device_grants', ['device_code_hash'])

    op.drop_index(op.f('ix_blocklist_items_uri_id'), table_name='blocklist_items')
    op.drop_index('idx_provider_cache_expires', table_name='provider_cache')
    op.drop_index('idx_media_aliases_internal_type', table_name='media_aliases')
    op.drop_table('episode_movie_conversions')
    op.drop_table('show_episode_overrides')
    op.drop_table('blocklist_items')
    op.drop_table('provider_cache')
    op.drop_table('media_aliases')
