"""add blur_explicit to user_settings

Revision ID: 5dbe314a6255
Revises: 0003_auto_sync_intervals
Create Date: 2026-04-29 11:05:06.456747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbe314a6255'
down_revision: Union[str, Sequence[str], None] = '0003_auto_sync_intervals'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('blur_explicit', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user_settings', 'blur_explicit')
    # ### end Alembic commands ###
