"""add comments and ratings toggles

Revision ID: cb25424a7781
Revises: b2c3d4e5f6a7
Create Date: 2026-05-08 19:44:01.253817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb25424a7781'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('show_comments', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user_settings', sa.Column('show_user_ratings', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'show_user_ratings')
    op.drop_column('user_settings', 'show_comments')
    # ### end Alembic commands ###
